
 image: node:12

 # Doing a full clone to be able to push back to Heroku.
 clone:
   depth: full

 pipelines:
   default:
       - step:
           caches:
             - node
           script:
             - npm install
             - git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
